### ISSUE TITLE
CREGEN clustering for a large structure

### ISSUE THREAD

**Issue by moabe84** [crest-lab/crest#258] opened 2024-02-05 18:09 UTC
Hi.
I'm trying to sort some conformations that I obtained from GFN-FF MTD simulations using the CREGEN tool. Each conformer has ~5000 atoms and there are 2000 conformers in each MTD trajectory. I have some question about expediting the analysis process:

1) How can I run CREGEN on multiple CPUs? I tried the "-T" command (with export MKL_NUM_THREADS), but did not work and still used one single CPU.  

2) Are there any other possibilities/features that I can apply to speed up the analysis? 

Thank you very much.

Best,
Mostafa

**Comment by pprcht** [comment] 2024-02-06 15:26
Unfortunately I think the issue is I/O based. Reading and writing this amount of data from disk will produce the overhead you are seeing here (and can't be parallelized, which is why only one core is running).
The actual CREGEN comparison of 2000 structures is quite fast, that's a moderate amount still.
Also I should warn, the conformer/rotamer distinction will not be good for systems of this size.

**Comment by moabe84** [comment] 2024-02-06 15:43
Thank you very much, Philipp. So I guess I'll need to run it on a SSD disk to make the I/O activities faster.

Regarding your point: " _Also I should warn, the conformer/rotamer distinction will not be good for systems of this size._", do you say that the CREGEN clustering approach, which is based on the energy, rotational constants, and Cartesian RMSDs, is not appropriate for large systems (like proteins) _in general_ and other suitable methods must be applied for such systems?   

Thanks,
Mostafa

**Comment by pprcht** [comment] 2024-02-06 17:05
Oh yes, if you are not running on an SSD it will be really slow I/O

The sorting still will produce something for proteins (and do the energetic sorting) but RMSDs and rotational constants will often be quite similar. Therefore the threshold based comparison will be inaccurate.

**Comment by moabe84** [comment] 2024-02-06 21:53
Great! You've been most helpful. Thank you.

**Closed** 2024-02-06 21:53 UTC
