### ISSUE TITLE
CREST 3.0+ Encounters Error and Gets Stuck During Conformational Search

### ISSUE THREAD

**Issue by lizhiq16** [crest-lab/crest#345] opened 2024-09-20 04:17 UTC
**Describe the bug**
When performing conformational searches using CREST version 3.0.1 or later, I have encountered an issue where the program reports an error (Intel MKL ERROR: Parameter 6 was incorrect on entry to DLASWP) but continues to run indefinitely (a search for a single molecule has lasted over two weeks without completion). However, when using CREST version 2.12, the same task is completed within 11 hours.

I acknowledge that this issue does not occur consistently, and I have successfully performed many conformational searches using CREST 3.0+. However, when I use the molecular structure provided in the attachment (1.xyz), I always encounter the same problem, even after switching to CREST 3.0.1 and CREST 3.0.2. The output when the issue occurs is attached for your reference.

 I hope the developers can investigate if there is any bug. 

**To Reproduce**
Use the geometry attached.
`crest 1.xyz --v3 --opt normal --quick --T 14 --niceprint`
[crest-error.zip](https://github.com/user-attachments/files/17069754/crest-error.zip)

**Comment by pprcht** [comment] 2024-09-20 14:27
Duplicate of #285

**Comment by pprcht** [comment] 2024-09-20 14:29
The original issue is pinned ...

This is caused by some nested parallelism mismatch between OpenMP and MKL, I have not found a 100% secure workaround so far.
You can try the gfortran/openblas version

**Closed by pprcht** 2024-09-20 14:29 UTC
Labels: bug
