### ISSUE TITLE
Error allocating memory - constrained portion

### ISSUE THREAD

**Issue by winston515** [crest-lab/crest#381] opened 2024-12-14 00:00 UTC
**Describe the bug**
I'm trying to perform a similar conformational sampling to TYR on graphene (as described https://crest-lab.github.io/crest-docs/page/examples/publication/example_3.html) where I want to sample the conformations of an inorganic compound atop a small section of a carbon nanotube. 
Every time I try to use --cinp to constrain the nanotube (as described at the link above and here: https://crest-lab.github.io/crest-docs/page/examples/example_4.html#fixing-of-entire-substructure-parts), I run into this error: 

In file '/home/runner/work/crest/crest/src/parsing/parse_xtbinput.f90', around line 720: Error allocating 2188448768777856 bytes: Cannot allocate memory

I thought maybe there was something wrong with my .xyz or coord files, but CREST runs fine with the same files when no constraints are involved in the command. I then thought it was my constraint input file, but even when I have CREST generate the .xcontrol.sample file for me and submit that as the constraint (which is the exact same text as my own constraints.inp file), it still gives me the same error. I've tried a lot of combinations and workarounds, but can't seem to get anything to run with constraints. 

Anyone else run into this? I'm new at this type of work. Thanks in advance for any help or guidance!

**To Reproduce**
Using Version 3.0.2 
203 molecules, trying to constrain molecules 61-203
I've tried a lot of different combinations for commands, but generally this is what I'm trying to specify:
crest coord --subrmsd --shake 0 --tstep 1 --cinp constraints.inp --gbsa h2o --gff 

**edit** 
I also just tried to reproduce the actual tyrosine on graphite example using the coordinates and commands given, and ran into the same error: 
In file '/home/runner/work/crest/crest/src/parsing/parse_xtbinput.f90', around line 720: Error allocating 2188448768777856 bytes: Cannot allocate memory

**Comment by pprcht** [comment] 2024-12-14 12:54
Duplicate of #338 and #367  

It has already been fixed in the main branch, but updates are not automatically adapted to conda or the release binary.

**Closed** 2024-12-17 11:35 UTC
Labels: bug
