### ISSUE TITLE
tautomerize failure with gff, success with other ffs

### ISSUE THREAD

**Issue by jessbade** [crest-lab/crest#290] opened 2024-04-23 17:41 UTC
I'm following example 5, with the same structure, using version 2.12.

Running: crest struc.xyz --tautomerize -gfn2 succeeds.  Running: crest struc.xyz --tautomerize -gfn1 succeeds. However, crest struc.xyz --tautomer -gff errors out in protonation cycle 1 with: 

 ***Warning***
 No "coordprot.0" file was written, it is possible that
 there are no suitable LP- or π-centers in the molecule.
 Hence the procedure could not be automatized. (sorry)
 ***Warning***

**Comment by pprcht** [comment] 2024-04-23 17:47
duplicate of #282

Unfortunately the force-field does not provide molecular orbitals used for finding suitable protonation sites and can not be used for `-tautomerize` and `-protonate`

**Closed as completed** 2024-04-23 19:47 UTC
